version: '3'

services:
  punchingbag:
    build:
      context: ./punching-bag
    restart: unless-stopped
    networks:
      funny:
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      funny:
    volumes:
      - gamerbot-store:/gb-data
    depends_on:
      - punchingbag

volumes:
  gamerbot-store:

networks:
  funny:
    driver: bridge